trigger:
- master

pool:
  name: Default
  vmImage: azure-vm-01

steps:
  - task: CmdLine@2
    displayName: Docker Build
    inputs:
      script: 'docker build -t backend:$(Build.BuildNumber) .'
      workingDirectory: 'src/backend'
  - task: CmdLine@2
    displayName: Docker Tag
    inputs:
      script: 'docker tag backend:$(Build.BuildNumber) $(ACR_ENDPOINT)/backend:$(Build.BuildNumber)'
  - task: CmdLine@2
    displayName: Trivy Scan
    inputs:
      script: 'trivy image --format template --template "~/templates/junit.tpl" -o trivy-scan-report.xml $(ACR_ENDPOINT)/backend:$(Build.BuildNumber)'
  - task: PublishTestResults@2
    displayName: Publish Trivy Scan
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/trivy-scan-report.xml'
      mergeTestResults: true
      failTaskOnFailedTests: false
      testRunTitle: 'Trivy Scan Report'
    condition: 'always()'   
  - task: CmdLine@2
    displayName: Docker Login
    inputs:
      script: 'docker login $(ACR_ENDPOINT) -u $(DockerUser) -p $(DockerPassword)'
  - task: CmdLine@2
    displayName: Docker Push
    inputs:
      script: 'docker push $(ACR_ENDPOINT)/backend:$(Build.BuildNumber)'
  - task: CmdLine@2
    displayName: Clean Image
    inputs:
      script: 'docker image prune -a -f'