trigger:
- master

pool:
  name: Dev01
  vmImage: az-dev01

steps:
  - task: CmdLine@2
    displayName: Docker Build
    inputs:
      script: 'docker build -f src/backend -t backend:$(Build.BuildNumber)'
  - task: CmdLine@2
    displayName: Docker Tag
    inputs:
      script: 'docker tag backend:$(Build.BuildNumber) acrloctranhc.azurecr.io/backend:$(Build.BuildNumber)'
  