pipeline {
  agent any
  stages {
    stage('Build Image') {
      steps {
        dir('src/frontend') {
          sh "docker build -t frontend:${BUILD_NUMBER} ."
          sh 'docker tag frontend:${BUILD_NUMBER} acrloctranhc.azurecr.io/frontend:${BUILD_NUMBER}'
        }
      }
    }
    stage('Push Image to ACR') {
      steps {
        withCredentials([usernamePassword(credentialsId: 'dockerHub', passwordVariable: 'dockerHubPassword', usernameVariable: 'dockerHubUser')]) {
          sh "docker login acrloctranhc.azurecr.io -u ${env.dockerHubUser} -p ${env.dockerHubPassword}"
          sh 'docker push acrloctranhc.azurecr.io/frontend:${BUILD_NUMBER}'
        }
      }
    }
    stage('Clean Image') {
      steps {
        sh 'docker image prune -a -f'
      }
    }
    stage('Replace File') {
      steps {
        contentReplace(
          configs: [
            fileContentReplaceConfig(
              configs: [
                fileContentReplaceItemConfig(
                  search: 'frontend-image',
                  replace: 'acrloctranhc.azurecr.io/frontend:${BUILD_NUMBER}',
                  matchCount: 1,
                  verbose: false,
                )
              ],
              fileEncoding: 'UTF-8',
              lineSeparator: 'Unix',
              filePath: 'frontend.yaml'
            )
          ]
        )
      }
    }
    stage('Deploy') {
      steps {
        sh 'kubectl apply -f frontend.yaml'
      }
    }
  }
}