pipeline {
    agent any
    triggers {
        githubPush()
    }

    stages {
        stage('Build Image') {
            steps {
                sh 'docker build -f /src/frontend -t fontend .'
            }
        }
        stage('Push Image to ACR') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}