pipeline {
    agent any

    stages {
        stage('Build Image') {
            steps {
                script{
                    sh 'ls'
                    sh 'docker build . -t frontend'
                }
            }
        }
        stage('Push Image to ACR') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}